-- Mahamagham 2027 V9 support/payment schema.
-- Run once in the intended Supabase project after review.
-- Public/anon clients receive no policies; writes happen only through server-side API functions.

create table if not exists public.support_enquiries (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  name text not null,
  phone text not null,
  email text,
  interest text,
  category text,
  message text,
  source text not null default 'website',
  status text not null default 'new' check (status in ('new','contacted','closed'))
);

create table if not exists public.support_intents (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  reference text not null unique,
  kind text not null,
  category text not null,
  name text not null,
  phone text not null,
  email text,
  message text,
  amount_paise bigint not null check (amount_paise > 0),
  currency text not null default 'INR',
  status text not null default 'creating_order',
  razorpay_order_id text unique,
  razorpay_payment_id text unique,
  verified_at timestamptz,
  source text not null default 'website'
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  intent_id uuid not null references public.support_intents(id) on delete restrict,
  razorpay_order_id text not null,
  razorpay_payment_id text not null unique,
  status text not null,
  verified_at timestamptz
);

create table if not exists public.payment_events (
  id bigint generated by default as identity primary key,
  received_at timestamptz not null default now(),
  event_id text unique,
  event_type text not null,
  payload jsonb not null
);

create index if not exists support_enquiries_created_at_idx on public.support_enquiries (created_at desc);
create index if not exists support_intents_created_at_idx on public.support_intents (created_at desc);
create index if not exists support_intents_status_idx on public.support_intents (status);
create index if not exists support_intents_order_idx on public.support_intents (razorpay_order_id);
create index if not exists payments_intent_idx on public.payments (intent_id);

alter table public.support_enquiries enable row level security;
alter table public.support_intents enable row level security;
alter table public.payments enable row level security;
alter table public.payment_events enable row level security;

-- No anon/authenticated policies are intentionally created.
-- Server-side secret/service-role access bypasses RLS; never expose that key in browser code.
